import { Inter } from "next/font/google";
import localFont from "next/font/local";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import "./globals.scss";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
  preload: true,
});

const gamePaused = localFont({
  src: [
    {
      path: "../fonts/GamePausedDEMO.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/GamePausedDEMO.otf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-gamepaused",
  display: "swap",
  preload: true,
});


export const metadata = {
  title: "Dance Verse",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable} ${gamePaused.variable}`}>
      <head>
        {/* Preload critical fonts manually with correct as attribute */}
        <link
          rel="preload"
          href="../fonts/GamePausedDEMO.woff2"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
      </head>
      <body >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
