import { Inter } from "next/font/google";
import localFont from "next/font/local";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

const gamePaused = localFont({
  src: [
    {
      path: "../fonts/GamePausedDEMO.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/GamePausedDEMO.otf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-gamepaused",
  display: "swap",
});


export const metadata = {
  title: "Dance Verse",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable} ${gamePaused.variable}`}>
      <body >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
